Add configuration for new domain name iris.ac.uk
cvmfs-contrib/config-repo pull request #104
Opened 2022-07-11 13:43 UTC by jose-caballero

Add the public key and config file for brand new domain name iris.ac.uk
As this is only for the UK, and there is currently no repository with that domain name, it is fine for the time being to use only the Stratum-1 at RAL.

2022-07-11 22:20 UTC, DrDaveD requested changes

2022-07-11 22:28 UTC, DrDaveD requested changes

2022-07-11 22:28 UTC, DrDaveD commented on etc/cvmfs/domain.d/iris.ac.uk.conf
> +. ../common.conf
Please add the 4 lines of prefix before including common.conf that is in all the other domain.d/*.conf files.

2022-07-12 06:56 UTC, jose-caballero commented
Fixed.

2022-07-12 16:58 UTC, DrDaveD approved these changes

2022-07-13 07:52 UTC, jose-caballero commented
Should I issue the Merge myself, or someone else from the CVMFS core team have to do it?

2022-07-13 12:03 UTC, DrDaveD commented
You do it, now that it is approved.

2022-07-13 12:05 UTC, merged