Adding Americas caches to OSG
cvmfs-contrib/config-repo pull request #182
Opened 2023-08-28 22:47 UTC by biozit

Adding Americas caches to OSG

2023-08-28 22:55 UTC, DrDaveD commented
Related to #181 .  For @jthiltges to approve, merge, and distribute.

2023-08-29 18:40 UTC, DrDaveD commented on etc/cvmfs/osgstorage-auth.conf
> +
It would be better to not add extra blank lines (also in osgstorage.org.conf)

2023-08-29 18:42 UTC, biozit commented
ok

2023-08-31 17:07 UTC, jthiltges requested changes

2023-08-31 17:09 UTC, biozit commented
@jthiltges fixed! Good catch!

2023-08-31 17:11 UTC, jthiltges approved these changes
LGTM, thanks!

2023-08-31 17:20 UTC, biozit reviewed
done

2023-08-31 18:58 UTC, merged

2023-09-01 18:18 UTC, jthiltges commented
Published to config-osg as rev 118.