restore setup for RAL Stratum-1
cvmfs-contrib/config-repo pull request #274
Opened 2024-12-06 10:26 UTC by jose-caballero

2024-12-06 13:07 UTC, DrDaveD commented
It's close but not quite ready for this yet, I am discussing it with the admin team. Also it isn't good to make a change of this magnitude just before a weekend.

2024-12-06 14:46 UTC, DrDaveD requested changes
This is the reverse of #264.  

After the one small change to this PR that I requested, I think now that the RAL stratum 1 service is in sufficiently good shape to be put into service early next week, even though there are more changes that should be done to it after that point.

2024-12-06 14:46 UTC, DrDaveD commented on etc/cvmfs/domain.d/kek.jp.conf
> +    CVMFS_SERVER_URL="http://cvmfs-stratum-one.cc.kek.jp:8000/cvmfs/@fqrn@;http://cernvmfs.gridpp.rl.ac.uk:8000/cvmfs/@fqrn@;http://grid-cvmfs-one.desy.de:8000/cvmfs/@fqrn@;http://cvmfs-s1bnl.opensci
While we're doing this let's change cernvmfs.gridpp.rl.ac.uk to cvmfs-egi.gridpp.rl.ac.uk for this domain, leaving the cernvmfs alias only for the cern.ch domain.

There's really little point to having the cernvmfs alias at all, but it is the name still used in the cvmfs-config-default rpm for the cern.ch domain so it should stay there.  The original idea of having two names was to be able to move the cern.ch repositories to a separate server if that was ever desired.  There's no point to having it be used for the kek.jp domain.

2024-12-09 07:16 UTC, jose-caballero commented
I have changed the aliases to use cvmfs-egi only

2024-12-09 15:32 UTC, DrDaveD approved these changes

2024-12-09 16:02 UTC, merged