Add KEK domain configuration
cvmfs-contrib/config-repo pull request #51
Opened 2021-03-03 22:24 UTC by jblomer

Replaces #47

2021-03-04 17:19 UTC, DrDaveD requested changes

2021-03-04 17:19 UTC, DrDaveD commented on etc/cvmfs/domain.d/kek.jp.conf
> +    CVMFS_SERVER_URL="http://cvmfs-stratum-one.cc.kek.jp:8000/cvmfs/@fqrn@;http://cernvmfs.gridpp.rl.ac.uk:8000/cvmfs/@fqrn@;http://grid-cvmfs-one.desy.de:8000/cvmfs/@fqrn@;http://cvmfs.racf.bnl.gov:
Please use cvmfs-s1fnal.opensciencegrid.org instead of cvmfs.racf.bnl.gov.  The latter is itself an alias to cover an old name for the server.

2021-03-09 22:53 UTC, DrDaveD approved these changes

2021-03-10 18:48 UTC, DrDaveD commented
Yes, although it's probably best to deploy it in default and test there a little while first.  osg isn't ready to merge yet but it's ok to have the PR ready and egi should be ready.  I'll also want a PR against the master branch although I usually take care of that myself.

2021-03-12 11:05 UTC, merged

2021-03-12 11:24 UTC, jblomer commented
This is now deployed in the /cvmfs/cvmfs-config.cern.ch in the `TESTING` branch. I'd like to also deploy #55 before giving it to the lxplus and lxbatch teams for testing.

2021-03-12 12:50 UTC, olifre commented
Many thanks for this effort also from our side — we are amongst the sites asked to mount the KEK repositories (on two resources), but we are not really delighted by the "one-shot-RPM" or "manual configuration" steps that were provided by the experiment. So having something in the config repository which is also updated when Squids change is really welcome :+1:.